language: rust
dist: xenial
os: linux

# Exclude wip-* branches which are expected to fail
branches:
  except:
  - /^wip-.*$/

cache:
  - cargo

rust:
  - stable

before_install:
  - openssl aes-256-cbc -K $encrypted_a11d45963b96_key -iv $encrypted_a11d45963b96_iv -in dpl.key.enc -out dpl.key -d

jobs:
  include:
    - name: Calypso Books
      before_script:
        - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
        - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.4" mdbook)
        - cargo install-update -a
        - rustup toolchain install nightly # This will install/update the nightly toolchain
      script:
        - cd docs
        - ./build-books.sh
      deploy:
        provider: pages
        cleanup: false
        deploy_key: "../dpl.key"
        local_dir: ./out
        keep_history: true
        edge: true
        target_branch: main
        name: Travis CI
        email: deploy@travis-ci.org
        repo: calypso-lang/calypso-lang.github.io
        on:
          branch: main
    - name: "Calypso/x86_64-unknown-linux-gnu"
      script:
        - cargo build --workspace --all-features --all-targets
        - cargo test --workspace --all-features --all-targets
    - name: "Calypso/1.48.0-x86_64-unknown-linux-gnu"
      rust: 1.48.0
      script:
        - cargo build --workspace --all-features --all-targets
        - cargo test --workspace --all-features --all-targets
    - name: "Calypso/nightly-x86_64-unknown-linux-gnu"
      rust: nightly
      script:
        - cargo build --workspace --all-features --all-targets
        - cargo test --workspace --all-features --all-targets
  allow_failures:
    - rust: nightly
