language: rust
dist: xenial
os: linux

cache:
  - cargo

rust:
  - stable

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.4" mdbook)
  - cargo install-update -a

script:
  - cd docs && rm -rf book
  - export MDBOOK_OUTPUT__HTML__site_url="/Calypso" && mdbook build .  && mdbook test .

deploy:
  provider: pages
  cleanup: false
  token: $GITHUB_TOKEN
  local_dir: ./book
  keep_history: false
  edge: true
  target_branch: gh-pages