language: rust
dist: xenial
os: linux

cache:
  - cargo

rust:
  - stable

before_install:
  - openssl aes-256-cbc -K $encrypted_a11d45963b96_key -iv $encrypted_a11d45963b96_iv -in dpl.key.enc -out dpl.key -d

jobs:
  include:
    - name: The Calypso Book
      before_script:
        - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
        - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.4" mdbook)
        - cargo install-update -a
        - rustup toolchain install nightly # This will install/update the nightly toolchain
      script:
        - cd docs && rm -rf book
        - export MDBOOK_OUTPUT__HTML__site_url="/Calypso" && mdbook build . && mdbook test .
        - cargo +nightly doc --workspace --no-deps
        - mv -f ../target/doc ./book/rustdoc
      deploy:
        provider: pages:git
        cleanup: false
        deploy_key: "./dpl.key"
        local_dir: ./book
        keep_history: false
        edge: true
        target_branch: main
        name: Travis CI
        email: deploy@travis-ci.org
        repo: calypso-lang/calypso.github.io
    - name: "Calypso/x86_64-pc-linux-gnu"
      script:
        - cargo build --workspace
        - cargo test --workspace
