[package]
name = "calypso"
version = "0.1.0"
authors = ["ThePuzzlemaker <tpzker@thepuzzlemaker.info>"]
edition = "2018"
description = "A (very work-in-progress) general-purpose interpreted language with built-in systems for cryptography, ciphers, and encodings, implemented with Rust."
readme = "README.md"
homepage = "https://github.com/calypso-lang/calypso/"
repository = "https://github.com/calypso-lang/calypso/"
license = "MIT"
keywords = ["interpreter"]
categories = ["development-tools", "parser-implementations"]

[dependencies]
clap = { version = "2.33.3", features = ["yaml"] }
ansi_term = "0.12.1"
calypso_parsing = { path = "libs/calypso_parsing", version = "0.1.0" }
calypso_diagnostic = { path = "libs/calypso_diagnostic", version = "0.1.0" }
calypso_repl = { path = "libs/calypso_repl", version = "0.1.0" }
odysseus = { path = "libs/odysseus", version = "0.1.0" }

[workspace]
exclude = ["libs/sublib_skeleton"]
